spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/sima-land
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  kafka:
    bootstrap-servers: "kafka-1:19092"
    topic:
      payment-service-topic:
        topic-name: "payment"
        partitions: 3
        replication-factor: 3
        min-in-sync-replicas: 2
      confirmation-service-topic:
        topic-name: "confirmation"
        partitions: 3
        replication-factor: 3
        min-in-sync-replicas: 2
logging:
  level:
    com: INFO
#    root: DEBUG
#    org.springframework: DEBUG
    org.hibernate: ERROR
camunda.bpm:
  enabled: true
  auto-deployment-enabled: true
  job-execution:
    enabled: true
  deployment-resource-pattern:
    - classpath*:**/*.bpmn
    - classpath*:**/*.bpmn20.xml
    - classpath*:**/*.dmn
    - classpath*:**/*.dmn11.xml
    - classpath*:**/*.form
  database:
    type: postgres
  table-prefix: camunda.
  schema-update: true

  generic-properties:
    properties:
      historyTimeToLive: P1D
  admin-user:
    id: 1
    password: admin
    firstName: Admin
  filter:
    create: All tasks
  authorization:
    enabled: true
#    javax.transaction: DEBUG